power <- read.table("household_power_consumption.txt",skip=1,sep=";")
names(power) <- c("Date","Time","Global_active_power","Global_reactive_power","Voltage","Global_intensity","Sub_metering_1","Sub_metering_2","Sub_metering_3")
dp <- subset(power,power$Date=="1/2/2007" | power$Date =="2/2/2007")
dp <- subset(power,power$Date=="1/2/2007" | power$Date =="2/2/2007")
dp$Date <- as.Date(dp$Date, format="%d/%m/%Y")
dp$Time <- strptime(dp$Time, format="%H:%M:%S")
dp[1:1440,"Time"] <- format(dp[1:1440,"Time"],"2007-02-01 %H:%M:%S")
dp[1441:2880,"Time"] <- format(dp[1441:2880,"Time"],"2007-02-02 %H:%M:%S")
plot(dp$Time,dp$Sub_metering_1,type="n",xlab="",ylab="Energy sub metering")
with(dp,lines(Time,as.numeric(as.character(Sub_metering_1))))
with(dp,lines(Time,as.numeric(as.character(Sub_metering_2)),col="red"))
with(dp,lines(Time,as.numeric(as.character(Sub_metering_3)),col="blue"))
legend("topright", lty=1, col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
title(main="Energy sub-metering")